### ISSUE TITLE
support permenant, destructive method to remove the table

### ISSUE THREAD

**Issue by llxiaoyuan** [Jamesits/dropWPBT#3]
Can support permenant, destructive method to remove the table ?

**Comment by Jamesits** [comment]
Yes, a general method is to extract the firmware with a programmer, remove the table or embed this program as a driver into the firmware (whatever is feasible) and reprogram the SPI flash. Note:

- exact steps vary from board to board, so I cannot give you any further help regarding the specific board you are using
- this is dangerous and you might damage the motherboard on the way
- If PSB, Sure Start or other similar technology is enabled, you might not be able to boot a modified firmware at all
